"use client";
import { useState } from "react";
import { rankEligibleAgents } from "@/lib/fulfillment";
import { DemoOrderBanner } from "@/components/demo-order-banner";

const candidates = [{ id:"a1",name:"Kisumu Farm Supply",inventory:82,distanceKm:7,reliability:96,deliveryCapacity:90,price:650,active:true },{ id:"a2",name:"Nyanza Inputs",inventory:150,distanceKm:19,reliability:91,deliveryCapacity:78,price:645,active:true },{ id:"a3",name:"Lake Basin Agro",inventory:8,distanceKm:4,reliability:93,deliveryCapacity:85,price:640,active:true }];
const assignment = rankEligibleAgents(candidates, 10)[0]!;
const stages = ["PENDING","AGENT ASSIGNED","ACCEPTED","PROCESSING","READY FOR DELIVERY","OUT FOR DELIVERY","DELIVERED","COMPLETED"];

export default function AgentDashboard(){const [stage,setStage]=useState(1);const [accepted,setAccepted]=useState(false);return <main className="agent"><aside><a className="brand" href="/">TRIMEX <small>INC.</small></a><p>AGENT PORTAL</p><a className="selected" href="#overview">Overview</a><a href="#orders">Orders <b>1</b></a><a href="#inventory">Inventory</a><a href="#revenue">Revenue</a><a href="#account">Account</a><footer>Signed in as<br /><strong>Kisumu Farm Supply</strong></footer></aside><section className="agentMain"><header><div><p className="eyebrow">Agent dashboard</p><h1>Good morning, Kisumu.</h1></div><span className="status">● Online & accepting orders</span></header><DemoOrderBanner view="agent" /><div className="agentStats"><article><span>New orders</span><strong>01</strong><small>Awaiting action</small></article><article><span>Processing</span><strong>04</strong><small>Active fulfillment</small></article><article><span>Low stock</span><strong>02</strong><small>Needs attention</small></article></div><section className="orders" id="orders"><div className="orderHead"><div><p className="eyebrow">New fulfillment request</p><h2>Order #TMX-1024</h2></div><span className="score">Assignment score {assignment.score}</span></div><div className="orderGrid"><div><span>Customer</span><strong>Farmer reference #F-4838</strong><span>Delivery location</span><strong>Maseno, Kisumu County</strong><span>Fulfillment deadline</span><strong>Today · 4:30 PM</strong></div><div><span>Order item</span><strong>Maize Seed H614 × 10</strong><span>Order value</span><strong>KES 6,500</strong><span>Match reasoning</span><strong>Stock available · 7 km away · 96% reliability</strong></div></div>{!accepted?<div className="orderActions"><button className="reject">Reject</button><button className="accept" onClick={()=>setAccepted(true)}>Accept order ↗</button></div>:<><div className="lifecycle">{stages.map((item,index)=><button className={index<=stage?"done":""} disabled={index>stage+1} onClick={()=>setStage(index)} key={item}><i>{index+1}</i>{item}</button>)}</div><div className="audit">Last update: {stages[stage]} · Kisumu Farm Supply · just now</div></>}</section><section className="inventory" id="inventory"><p className="eyebrow">Inventory signal</p><h2>Maize Seed H614</h2><div><strong>82 bags</strong><span>Available inventory</span><button>Manage inventory ↗</button></div></section></section></main>}
