const layers = [
  ["01", "Inputs", "Access agricultural inputs through a connected fulfillment network."],
  ["02", "Services", "Bring practical agricultural services closer to every farm."],
  ["03", "Markets", "Connect production to buyers, demand and market opportunity."],
  ["04", "Trade", "Aggregate and move commodities into larger markets."],
];

export default function Home() {
  return <main>
    <section className="hero" id="top"><video className="video" autoPlay loop muted playsInline aria-hidden="true"><source src="/hero-page.mp4" type="video/mp4" /></video><div className="veil" />
      <nav><a className="brand" href="#top">TRIMEX <small>INC.</small></a><div className="links"><a href="/platform">Platform</a><a href="/farmers">For Farmers</a><a href="/agents">For Agents</a><a href="/markets">Markets</a><a href="/journal">Journal</a><a href="/access">Portals</a></div><a className="navButton" href="/partner">Partner with Trimex ↗</a></nav>
      <div className="heroCopy"><p className="eyebrow light">African agricultural infrastructure</p><h1>Feeding Africa<br />and the World.</h1><p>Trimex connects farmers, suppliers, agents, services and markets through one intelligent agricultural network.</p><div className="actions"><a className="button lime" href="/platform">Explore the platform ↘</a><a className="lineLink" href="/partner">Partner with Trimex ↗</a></div></div><div className="heroFoot"><span>SCROLL TO DISCOVER</span><span>NAIROBI · KENYA</span></div>
    </section>
    <section className="section intro" id="platform"><p className="eyebrow">The Trimex platform</p><div className="introGrid"><h2>Building the digital infrastructure for African agriculture.</h2><p>Africa&apos;s agricultural economy is massive. Its infrastructure is fragmented. Trimex is building the connected layer that lets people, products and opportunity move with greater confidence.</p></div><div className="stats"><div><b>One</b><span>connected platform</span></div><div><b>Five</b><span>agricultural layers</span></div><div><b>Built for</b><span>millions of farmers</span></div></div></section>
    <section className="section network" id="network"><p className="eyebrow light">The network</p><h2>One network. Multiple layers of agriculture.</h2><div className="diagram"><span>FARMERS</span><span>AGENTS</span><strong>TRIMEX<small>PLATFORM</small></strong><span>SUPPLIERS</span><span>SERVICES</span><span>MARKETS</span><span>TRADE</span></div><p className="caption">A connected system where every part of agriculture can work more intelligently together.</p></section>
    <section className="section"><div className="heading"><div><p className="eyebrow">Built to connect</p><h2>Technology across the agricultural value chain.</h2></div><p>Designed for the work happening now, and the agricultural economy Africa is building next.</p></div><div className="layers">{layers.map(([number,title,body])=><article key={title}><span>{number}</span><h3>{title}</h3><p>{body}</p><a href={title === "Markets" || title === "Trade" ? "/markets" : "/platform"}>↗</a></article>)}</div></section>
    <section className="section markets" id="markets"><p className="eyebrow">Markets & trade</p><div className="marketGrid"><div><h2>Connecting agricultural production to opportunity.</h2><p>From the farm gate to larger markets, Trimex enables the movement of produce, information and trust.</p><a className="button dark" href="/markets">Explore markets ↗</a></div><div className="flow">Farmer <i>↓</i> Production <i>↓</i> Aggregation <i>↓</i> Trade <i>↓</i> Buyer</div></div></section>
    <section className="section journal" id="journal"><div className="heading"><div><p className="eyebrow">Trimex Journal</p><h2>Ideas, intelligence and stories shaping African agriculture.</h2></div><a className="lineLink darkLink" href="/journal">Explore the Journal ↗</a></div><div className="articles">{["The connected future of agricultural trade","Why fulfillment is infrastructure","Building networks that work closer to the farm"].map((title,i)=><article key={title}><span>{["MARKETS","INSIGHTS","FARMERS"][i]} · 2026</span><h3>{title}</h3><a href="/journal">Read article ↗</a></article>)}</div></section>
    <section className="final" id="partner"><p className="eyebrow light">Trimex Inc.</p><h2>The future of African agriculture will be connected.</h2><p>Trimex is building the network.</p><a className="button lime" href="/partner">Join the Trimex network ↗</a></section><footer><a className="brand" href="#top">TRIMEX <small>INC.</small></a><span>© 2026 Trimex Inc.</span><span>Feeding Africa and the World.</span></footer>
  </main>;
}
